version: '3.8'

services:
  # PostgreSQL数据库
  postgres:
    image: postgres:15-alpine
    container_name: usercenter-postgres
    environment:
      POSTGRES_DB: usercenter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - usercenter-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: usercenter-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - usercenter-network

  # 后端应用
  backend:
    build: .
    container_name: usercenter-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - GIN_MODE=release
    volumes:
      - ./uploads:/root/uploads
      - ./logs:/root/logs
    networks:
      - usercenter-network

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: usercenter-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - usercenter-network

volumes:
  postgres_data:
  redis_data:

networks:
  usercenter-network:
    driver: bridge
